version: "3.8"

services:
  tfidf_svc:
    build:
      context: .
      dockerfile: docker/tfidf_svc.Dockerfile
    container_name: tfidf_svc
    ports:
      - "8000:8000"
    volumes:
      - ./src/tfidf_svc/:/app/src/tfidf_svc/
    environment:
      - PYTHONUNBUFFERED=1

  transformer:
    build:
      context: .
      dockerfile: docker/transformer.Dockerfile
    container_name: transformer_svc
    ports:
      - "8001:8000"   # expose le service Transformer sur le port local 8001
    volumes:
      - ./src/transformer/:/app/src/transformer/
      - ./models/transformer:/app/model:ro   # MONTE ICI ton modèle entrainé (read-only)
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_DIR=/app/model